### ISSUE TITLE
Provide a build compatible with kotlinx-serialization 1.2.1

### ISSUE THREAD

**Issue by jpd236** [Him188/yamlkt#27]
The current build is incompatible due to https://youtrack.jetbrains.com/issue/KT-46598; if you try to use it with kotlinx-serialization-core 1.2.1 and a Javascript project, you'll get an error:

```
Module not found: Error: Can't resolve 'kotlinx-serialization-kotlinx-serialization-core-jsLegacy' in '[path\to\project]\build\js\node_modules\yamlkt'
```

The project needs to be rebuilt to use the expected file path for legacy JS files.

**Comment by Him188** [comment]
Unfortunately, Kotlin 1.5.10 cannot compile yamlkt due to some regression of the compiler.

**Comment by jpd236** [comment]
Seems like the build is still failing with 1.5.20. Would it make sense to report this to the Kotlin issue tracker so they're aware?

At the moment, I believe this the only thing preventing my own project from migrating to 1.5, so would be great to get it resolved (or at least get the process started for an upstream fix).

This is the error I saw with 1.5.20 when running `./gradlew :yamlkt:compileKotlinJvm`, assuming you're seeing the same thing:  https://pastebin.com/i6YAzqEf

**Comment by jpd236** [comment]
Another observation is that removing the `@InlineOnly` annotations in the `foldFromRightOffsetIndexed` seems to work around the issue. Uploaded #30 which does this and otherwise touches as little as possible to get the tests to pass. Not at all sure of the impact of removing this annotation, but hopefully this is at least helpful in identifying the issue (and perhaps in finding a better workaround).
