### ISSUE TITLE
Floats are being converted to integers / longs

### ISSUE THREAD

**Issue by ncipollo** [Him188/yamlkt#28]
It appears that floating point numbers are being converted into either integers or longs (depending upon the value of the float). I'm not sure if this is generally the case, but it definitely seems to be happening when I am using `YamlDynamicSerializer.deserialize`. 

I believe I've tracked the issue to `String.adjustDynamicString`.  It looks like this method checks to see if the `double` value is within the max integer and max long ranges. If you pick a value like `3.1415` this will satisfy the integer condition and therefor be converted to an integer (and in so, losing significant digits).

You might be able to use the `rem` function to check to see if the number is in fact representing a float or an integer number - https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-int/rem.html .

**Comment by Him188** [comment]
Thank you for catching this! I will fix it soon.
