### ISSUE TITLE
Null values don't work; ensuing keys are skipped

### ISSUE THREAD

**Issue by jpd236** [Him188/yamlkt#3]
According to https://yaml.org/type/null.html, it is valid to have yaml like:

```yaml
nullable:
nonnull: value
```

where "nullable" has a null value, which is distinct from being absent from the YAML file, or present with an empty string value.

However, the following test:

```kotlin
    @Test
    fun testNullValue() {
        @Serializable
        data class TestData(
            val nullable: String?,
            val nonnull: String)

        assertEquals(TestData(null, "value"), default.parse(
            TestData.serializer(), """
                nullable:
                nonnull: value
            """.trimIndent()))
    }
```

Fails with "Field 'nonnull' is required, but it was missing".

**Comment by Him188** [comment]
`nonnull: value` is mistaken as a map.
I will add identation check for it.
