### ISSUE TITLE
README的语言及部分内容的完善

### ISSUE THREAD

**Issue by WutzuBert** [Him188/yamlkt#38]
README用英文编写，对于我这类中国开发者来说有些费解。
其次，既然作为JVM语言，还请作者放出Java的实现方法，不然我还需要在脑子里把kotlin转换成java。
谢谢

**Comment by Him188** [comment]
GitHub 是国际社区, 使用英语没有问题. 该项目没有正式版, 现在写文档以后都会改, 写多个语言没有意义

yamlkt 是为 kotlinx-serialization 写的 YAML 支持, 该库不设计为支持 Java
