### ISSUE TITLE
Which deps are used for js and native?

### ISSUE THREAD

**Issue by westnordost** [Him188/yamlkt#39]
I see in the build.gradle that snakeyaml is used for JVM but I couldn't find which dependency is used for parsing YAML on JS and Native. This is maybe something that could be put into the README along with any instructions if necessary how to use it on JS / Native. E.g. currently the README just says

> If your project is multiplatform, you need only to add this dependency for commonMain.

and to be honest, I don't really understand this sentence. Could you clarify this?

**Comment by Him188** [comment]
Thank you. Just add 
```kotlin
commonMain {
    dependencies {
        implementation("net.mamoe.yamlkt:yamlkt:0.10.2")
    }
}
```

Kotlin will automatically choose the dependency for each platform.

**Comment by westnordost** [comment]
Ah I see, but which dependencies for YAML parsing are used on Native and JS?

**Comment by Him188** [comment]
`net.mamoe.yamlkt:yamlkt-js` for JS and `net.mamoe.yamlkt:yamlkt-macosx64` for native macOS x64 (and `-mingwx64` for Windows, respectively).

**Comment by westnordost** [comment]
Oh, you created yamp parsing and writing libraries for javascript and native yourself? Ok, thanks!
