### ISSUE TITLE
Internal bad indent error in BlockMap serialization for nulls

### ISSUE THREAD

**Issue by StarWishsama** [Him188/yamlkt#5]
Original data class: https://paste.ubuntu.com/p/H3Q68Fk6Xy/
Error log: https://paste.ubuntu.com/p/mYvK6XrbtJ/

Kotlin JVM version: 1.3.72
KotlinX Serialization version: 1.3.72
yamlkt version: 0.3.2

Same error occurred when remove all `@Comment` annotations.

**Comment by Him188** [comment]
It seems to be an issue form `@Comment` annotation.

**Comment by Him188** [comment]
The problem is the nullability mark `?` in `String?`. Probably `\n` is absent after serializing a `null`.

**Comment by Him188** [comment]
To reproduce:
```kotlin
@Serializable
data class Config(
     var rConUrl: String? = null,
)
```

Serial result:
```yaml
rConUrl: null{}
```

**Comment by StarWishsama** [comment]
Another issue happened after i used 0.3.3, It seems like enum class can't be serialized properly.
Used same data class, can reproduced whether or not use `@Comment`, here's code of some related classes:

`enum class MusicApi {
    QQ, NETEASE
}`

In TestClass:
`println(Yaml.default.stringify(Config()))`

Error log: https://pastebin.com/dZSuEStA

**Comment by Him188** [comment]
Enum classes might not be supported yet, or it's due to the same issue as #5.

It requires a review of all `Encoder`s internally in yamlkt. I will open another issue for it.

**Comment by Him188** [comment]
Please subscribe #6 for continued information.

**Comment by Him188** [comment]
I meet with this problem also...I will now work on it.
