### ISSUE TITLE
Review internal encodeEnum and encodeValue in AbstractEncoder

### ISSUE THREAD

**Issue by Him188** [Him188/yamlkt#6]

**Comment by Him188** [comment]
To check whether it is fixed, use the enum example from #5 .

**Comment by Him188** [comment]
Test case: 
```kotlin
enum class MusicApi { QQ, NETEASE }
@Serializable
data class Config(
    var musicApi: MusicApi = MusicApi.QQ,
)
```

Serial result: 
```yaml
musicApi: QQ{}
```

**Comment by StarWishsama** [comment]
Still can't encodeString with #5 example, Error log here: https://pastebin.com/yNxEQx9q

But it works when only have enum in data class. Not whether it related to this issue.

Example:
`@Serializable
data class TestClass(var musicApi: MusicApi = MusicApi.QQ, var testString: String = "1")`

log: https://pastebin.com/3rth7Lca

**Comment by Him188** [comment]
I will investigate more.

**Comment by Him188** [comment]
There is some problem with the Kotlin debugger.
![image](https://user-images.githubusercontent.com/12100985/91725081-ce97c800-ebd0-11ea-9418-ab93d866b59b.png)

It's extremely hard for me to debug it.
