### ISSUE TITLE
Unable to use the lib 0.4.0 in Native

### ISSUE THREAD

**Issue by sebasborda** [Him188/yamlkt#7]
Hi, I'm trying to add the lib to my project multiplatform, it is working for js and jvm, but when I try to add it to common or directly to native (macosX64) it is returning the following error.

Could not resolve net.mamoe.yamlkt:yamlkt:0.4.0.

Thanks for your time.

**Comment by Him188** [comment]
Thank you for your report.

Kotlin/Native targeting macOS requires the library to be compiled also on macOS. However, I don't have such a machine...

I will probably try GitHub actions.

**Comment by sebasborda** [comment]
👍 Let me know if I can help you with something, at least testing it.

**Comment by Him188** [comment]
I have now released 0.4.1 with all native targets:
![image](https://user-images.githubusercontent.com/12100985/91586236-a8331c00-e987-11ea-8130-85e7cc54ce78.png)
